let allSongs = [
  {
    name: "Kun Faya Kun-Rockstar",
    artist: "A.R. Rahman, Javed ali, Mohit Chauhan",
    img: "music1",
    src: "music1",
  },
  {
    name: "Night Changes",
    artist: "One Direction",
    img: "music2",
    src: "music2",
  },
  {
    name: "Memories",
    artist: "Maroon 5",
    img: "music3",
    src: "music3",
  },
  {
    name: "Anuvanuvuu-Om Bheem Bhush",
    artist: "Arijit Singh, Sunny M.R, Krishna Kanth",
    img: "music4",
    src: "music4",
  },
  {
    name: "khairiyat-Chhichhore",
    artist: "Pritam, Arijit Singh",
    img: "music5",
    src: "music5",
  },
  {
    name: "Adigaa-Hi Nanna",
    artist: "Karthik, Ayshath Safa",
    img: "music6",
    src: "music6",
  },
  {
    name: "Who Says",
    artist: "Salena Gomez & The Scene",
    img: "music7",
    src: "music7",
  },
  {
    name: "Stay",
    artist: "The Kid LAROI, Justin Bieber",
    img: "music8",
    src: "music8",
  },
  {
    name: "Nadaan Parinde-Rockstar",
    artist: "A.R Rahman, Mohit Chauhan",
    img: "music1",
    src: "music9",
  },
  {
    name: "Lover",
    artist: "Taylor Swift",
    img: "music10",
    src: "music10",
  },
  {
    name: "Perfect",
    artist: "Ed Sheeran",
    img: "music11",
    src: "music11",
  },
  {
    name: "Dekhha Tenu",
    artist: "Mohammad faiz",
    img: "music12",
    src: "music12",
  },
  {
    name: "Satranga ,Animal",
    artist: "Arijit Singh",
    img: "music13",
    src: "music13",
  },
  {
    name: "kannuladha",
    artist: "Anirudh Ravichander",
    img: "music14",
    src: "music14",
  },
  {
    name: "Naa favourite Naa pellam",
    artist: "Adithya RK",
    img: "music15",
    src: "music15",
  },
  {
    name: "avununavaa",
    artist: "Leon James",
    img: "music16",
    src: "music16",
  },
  {
    name: "ninnu chuse Anandamlo",
    artist: "Anirudh Ravichander",
    img: "music17",
    src: "music17",
  },
  {
    name: "Yedhalo Oka Mounam",
    artist: "Anirudh Ravichander",
    img: "music18",
    src: "music18",
  },
  {
    name: "Sajni",
    artist: "Ram Sampath",
    img: "music19",
    src: "music19",
  },

  {
    name: "Dandelions",
    artist: "Ruth B.",
    img: "music21",
    src: "music21",
  },
  {
    name: "Agar Tum Saath Ho",
    artist: "Arijit Singh",
    img: "music22",
    src: "music22",
  },
  {
    name: "kalalo kooda",
    artist: "Tanishk Bagchi , Sid Sriram",
    img: "music23",
    src: "music23",
  },
  {
    name: "Ninnila",
    artist: "Thaman S",
    img: "music24",
    src: "music24",
  },
];
